MyDjango/urls.py
from django.urls import path, include
urlpatterns = [
    # 指向index的路由文件urls.py
    path('', include(('index.urls', 'index'), namespace='index')),
]

index/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # 定义路由
    path('', index.as_view(), name='index'),
]

index/models.py
from django.db import models

# Create your models here.
class PersonInfo(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    age = models.IntegerField()

index/views.py
from django.views.generic import ListView
from .models import PersonInfo
class index(ListView):
    # 设置模板文件
    template_name = 'index.html'
    # 设置模型外的数据
    extra_context = {'title': '人员信息表'}
    # 查询模型PersonInfo
    queryset = PersonInfo.objects.all().order_by('id')
    # 每页显示一条数据
    paginate_by = 1
    # 若不设置，则模板上下文默认为PersonInfo_list
    # context_object_name = 'Personinfo'

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
<body>
    <h3>{{ title }}</h3>
    <table border="1">
      {% for i in personinfo_list %}
          <tr>
            <th>{{ i.name }}</th>
            <th>{{ i.age }}</th>
          </tr>
      {% endfor %}
    </table>
    <br>
    {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="/?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="/?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
            <br>
            <br>
            <span class="page-current">
                第{{ page_obj.number }}页,共{{ page_obj.paginator.num_pages }}页。
            </span>
        </span>
    </div>
    {% endif %}
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<form enctype="multipart/form-data" action="" method="post">
{#    Django的CSRF防御机制#}
    {% csrf_token %}
    <input type="file" name="myfile"/>
    <input type="submit" value="上传文件"/>
</form>
</body>
</html>